name: Update on folder1
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Output Information
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.path }}
      - name: List changed directory
        run: ls -l ${{ github.workspace }}