name: Update on folder1
on:
#  push:
#    paths:
#      - '**/folder1/*'
  workflow_dispatch:

jobs:
  deploy-changed-yamls:
    env:
      TEST_SECRET: '${{secrets.TEST_SECRET}}'

    steps:  
    - uses: mschmalzbauer/actions-test/.github/workflows/deploy-to-rke2.yaml@main
      with:
        path: folder1
        branch_name: ${{ github.ref_name }}