name: Update on folder2
on:
  push:
    paths:
      - '**/folder2/*'
jobs:
  deploy-changed-yamls:
    uses: mschmalzbauer/actions-test/.github/workflows/deploy-to-rke2.yaml@main
    with:
      path: folder2