name: Update on folder1
on:
#  push:
#    paths:
#      - '**/folder1/*'
  workflow_dispatch:

env:
  TEST_SECRET: '${{secrets.TEST_SECRET}}'
  OTHER_TEST: 'ENV12'

jobs:
  deploy-changed-yamls:
    uses: mschmalzbauer/actions-test/.github/workflows/deploy-to-rke2.yaml@main
    with:
      path: folder1
      branch_name: ${{ github.ref_name }}
      other_test: ${{ env.OTHER_TEST }}