name: Deployment
run-name: "[${{ inputs.env }}] - Terraform Deployment"

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - dev
          - int
          - prod
    
jobs:
  checkout:
    uses: mschmalzbauer/.github/workflows/checkout@main
