name: Deployment
run-name: "[${{ inputs.env }}] - Terraform Deployment"

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - dev
          - int
          - prod
    
jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Branch
        if: ${{ inputs.env == 'dev' && ! startsWith(github.ref, 'refs/heads/maint') && ! startsWith(github.ref, 'refs/tags') ||
                inputs.env == 'int' && startsWith(github.ref, 'refs/heads/maint') ||
                inputs.env == 'prod' && startsWith(github.ref, 'refs/tags') }}
        id: check_branch
        run: |
          echo "deployment_env=${{ inputs.env }}" >> $GITHUB_OUTPUT
          
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Next Step
        if: ${{ steps.check_branch.outputs.deployment_env != '' }}
        run: |
          echo ${{ steps.check_branch.outputs.deployment_env }}

      - name: Tagging
        if: ${{ steps.check_branch.outputs.deployment_env == 'int' }}
        run: |
          git config --global user.email "michael@example.com"
          git config --global user.name "Michael"
          git tag -a v1.0 -m "Version 1.0"
          git push origin v1.0
        
      - name: Calculate Result
        if:  ${{ steps.check_branch.outputs.deployment_env == '' }}
        run: |
          echo "Deployment prerequisite not met!"
          echo "Environment: ${{ inputs.env}}"
          echo "Branch/Tag ${{ github.refs}}"
          exit 1
