name: Deployment

on:
  workflow_dispatch:
    
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repos via Composite Action
        uses: mschmalzbauer/.github/actions/checkoutRepo@main