name: Deployment

on:
  workflow_dispatch:
    
jobs:
  checkout:
    runs-on: ubuntu-latest

    environment: 'dev'
    
    steps:
      - name: Checkout Branch
        run: |
          if [ "${{ inputs.env }}" == "dev" ]; then
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "Starting DEV Deployment on main Branch."
            else
              echo "DEV deployment only allowed on main Branch!"
              exit 1
            fi
          fi
