name: Deployment
run-name: "[${{ inputs.env }}] - Terraform Deployment"

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - dev
          - int
    
jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Branch
        if: ${{ inputs.env == 'dev' && ! startsWith(github.ref, 'refs/heads/maint') && ! startsWith(github.ref, 'refs/tags') ||
                inputs.env == 'int' && startsWith(github.ref, 'refs/heads/maint') }}
        id: check_branch
        run: |
          echo "deployment_env=${{ inputs.env }}" >> $GITHUB_OUTPUT

      - name: Next Step
        if: ${{ steps.check_branch.outputs.deployment_env != '' }}
        run: |
          echo ${{ steps.check_branch.outputs.deployment_env }}
          
      - name: Calculate Result
        if:  ${{ steps.check_branch.outputs.deployment_env == '' }}
        run: |
          echo "Deployment prerequisite not met!"
          echo "Environment: ${{ inputs.env}}"
          echo "Branch/Tag ${{ github.refs"
          exit 1
