name: Deployment
run-name: "[${{ inputs.env }}] - Terraform Deployment"

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - dev
          - int
          - prod
      version:
        type: string
        description: Version to tag the repository with (only INT Deployment)
    
jobs:
  deployment:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest
    
    steps:
      - name: Deployment
        uses: mschmalzbauer/.github/actions/deployment@main
        with:
          env: ${{ inputs.env }}
          version: ${{ inputs.version }}
