name: Deploy to RKE2
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      branch_name:
        required: true
        type: string
      other_test:
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: List changed directory
        run: |
          echo ${{ inputs.branch_name }}
          echo "==="
          echo ${{ env.TEST_SECRET }}
          echo "==="
          echo ${{ env.OTHER_TEST }}
          echo "==="
          echo ${{ inputs.other_test }}
          ls -l ${{ github.workspace }}/${{ inputs.path }}