name: Deployment

on:
  workflow_dispatch:
    
jobs:
  checkout:
    runs-on: ubuntu-latest

    environment: 'dev'
    
    steps:
      - name: Check Branch
        uses: mschmalzbauer/.github/actions/checkBranch@main
