name: Deployment

on:
  workflow_dispatch:
    
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@3

  checkout_2:
    uses: mschmalzbauer/.github/.github/workflows/checkout.yaml@main

#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout Repos via Composite Action
#        uses: mschmalzbauer/.github/actions/checkoutRepo@main