name: Deployment
run-name: "[${{ inputs.env }}] - Terraform Deployment"

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - dev
          - int
          - prod
    
jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Branch
        uses: mschmalzbauer/.github/actions/checkoutRepo@main
        with:
          env: $ {{ inputs.env }}
        
      - name: Tagging
        uses: mschmalzbauer/.github/actions/tagging@main
        with:
          env: $ {{ inputs.env }}
