name: Deployment

on:
  workflow_dispatch:
    
jobs:
  checkout:
    runs-on: ubuntu-latest

    environment: 'dev'
    
    steps:
      - name: Checkout Branch
        run: |
          echo "${{ github.ref }}"
          if [ ${{ contains(github.ref, '/maint') }} ]; then
            echo "Starting Deployment on ${{ github.ref }} Branch."
          else
            echo "Deployment only allowed on a maint Branch!"
            exit 1
          fi
