name: Deployment

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - dev
          - int
    
jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Branch
        if: ${{ inputs.env == 'dev' && ! startsWith(github.ref, 'refs/heads/maint') && ! startsWith(github.ref, 'refs/tags') }}
        id: check_branch
        outputs:
          deployment_env:
            value: ${{ steps.chck_branch.outputs.deployment_env }}
        run: |
          echo "${{ inputs.env }}" >> $GITHUB_OUTPUT

      - name: Next Step
        run: |
          echo ${{ steps.chck_branch.outputs.deployment_env }}
