name: Deploy to RKE2
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: List changed directory
        run: ls -l ${{ github.workspace }}/${{ inputs.path }}