name: Deployment

on:
  workflow_dispatch:
    
jobs:
  checkout:
    runs-on: ubuntu-latest

    environment: 'dev'
    
    steps:
      - name: Checkout Branch
        run: |
          if [[ ${{ contains(github.ref, 'refs/heads/main') ]]; then
            echo "Starting Deployment on main Branch."
          else
            echo "Deployment only allowed on main Branch!"
            exit 1
          fi
