name: Deployment

on:
  workflow_dispatch:
    
jobs:
  checkout:
    runs-on: ubuntu-latest

    environment: 'dev'
    
    steps:
      - name: Checkout Branch
        run: |
          if [[ ! ${{ contains(github.ref, 'maint') }} ]]; then
            echo "No Deployment started."
          else
            echo "Starting Deployment on ${{ github.ref }} Branch."
            exit 1
          fi
