name: Development Workflow

on:
  workflow_dispatch:
    
jobs:
  prepare_environment:
    runs-on: ubuntu-latest
    environment: dev
    env:
      MY_VAR: ${{ vars.VAR_1 }}      

  output_environment:
    uses: ./.github/workflows/env-secrets-test.yaml
