name: Integration Workflow

on:
  push:
    paths:
      - 'environment/int/**'
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform
    # uses: ./.github/workflows/env-secrets-test.yaml
        uses: ./ .github/actions/executeTerraform