name: Integration Vars Test

on:
  push:
    paths:
      - 'environment/int/**'
  workflow_dispatch:
    inputs:
      env:
        required: true
        options:
        - dev
        - int
    
jobs:
  echo_env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: output_env
        run: printenv
